services:
  chrome:
    image: chromedp/headless-shell:130.0.6723.6
    # command: /headless-shell/headless-shell chromedp/headless-shell --remote-debugging-address=0.0.0.0 --remote-debugging-port=9992 --disable-gpu --headless


  server:
    build:
      context: .
    command: /usr/bin/deno run --allow-net --allow-env --allow-read --unstable --watch src/index.ts
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      - CHROME_PORT=9222
      - CHROME_HOSTNAME=chrome
      - AUTHORIZATION_KEY=1234567890
